### ISSUE TITLE
Rework the "`attrs.field or def`" syntax

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nix#7112]
**Is your feature request related to a problem? Please describe.**

There are a couple of issues with the current implementation:
- `or` parses only as part of the `.` syntax as an operator, else it's assumed that it's a function leading to not user friendly error messages like "undefined variable 'or'" because it's parsed as a function. Given that `or` is *indeed* defined that will lead to even more unexpected error messages. and behaviour, e.g.
```nix 
or = x: x 

{a="a";}.a or "b" 
# evaluates to "b"
({a="a";}.a) or "b" 
# evaluates to 
# error: attempt to call something which is not a function but a string
# 
#        at «string»:1:1:
# 
#             1| ({a="a";}.a) or "a"
#              | ^
```
Another issue with this is, that there's common breakages of syntax highlighting. 

I also don't think it's a useful feature as it saves minimal amounts of work in some cases and defining `or` would probably considered bad practice anyway. 

- with `or`, the thing that is accessed doesn't need to be an attrset, which makes things like 
```nix
"".a or "b"
```
possible. I think this is an issue as the language doesn't have a strong type system anyway and allowing any type to be part of the `.` syntax with `or` will cause unexpected defaulting. 

Indeed, without `or`, `"".a` would err. This is imho inconsistent. 

I also think it's unnecessary as you could simulate this behavior very easily with checking for type with `isAttrs` first. 

**Describe the solution you'd like**
- `.` only works on attrsets, in *all* cases
- `or` becomes a reserved keyword that cannot be used in any other context 

Thanks so much for you consideration!

**Comment by L-as** [comment]
I am very much against making breaking changes to the language.

**Comment by brainrake** [comment]
- make `or` reserved keyword
-

**Comment by NobbZ** [comment]
This is a breaking change, as `{ or = 1; }` becomes invalid all of a sudden. This might be relevant for handwritten nix expressions that are converted to YAML or JSON.

**Comment by MangoIV** [comment]
> `{ or = 1; }` becomes invalid all of a sudden

this is arguably abuse, too. neither would you be able to write `{ let = 1; }` or idk `{ = = 1; }`, there's a very simple fix though, just put it in `"`...

**Comment by brainrake** [comment]
you can still write `{ "or" = 1; }`

**Comment by NobbZ** [comment]
Yes, you can still do that, though you have to change code.

You are arguing that this is not a breaking change, and I did nothing but tell you "it is".

**Comment by brainrake** [comment]
Got it, thank you for clarifying.

**Comment by aameen-tulip** [comment]
> This is a breaking change, as `{ or = 1; }` becomes invalid all of a sudden. This might be relevant for handwritten nix expressions that are converted to YAML or JSON.

I use this as `{ "or" = ...; }` just to be defensive but I agree that making `or` an invalid key would be annoying

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
