### ISSUE TITLE
Build failure: closure.hh -Wchanges-meaning errors after PR #15474

### ISSUE THREAD

**Issue by randomizedcoder** [NixOS/nix#15499]
## Description

`origin/master` (commit 256877095) fails to build with GCC 14.3.0 due to `-Wchanges-meaning` errors in `src/libutil/include/nix/util/closure.hh`.

This appears to have been introduced by PR #15474 (`async-for-days`), specifically commit `47d2d18` ("Make computeClosure async").

The previous master (`04e261a2a`, before the merge of #15474) builds cleanly.

## Error output

```
FAILED: [code=1] src/libstore/libnixstore.so.2.35.0.p/http-binary-cache-store.cc.o 
../src/libutil/include/nix/util/closure.hh:39:32: error: declaration of 'decltype (executor) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:72)>::State::executor' changes meaning of 'executor' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:40:32: error: declaration of 'decltype (getEdges) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:72)>::State::getEdges' changes meaning of 'getEdges' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:41:31: error: declaration of 'decltype (handler) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:72)>::State::handler' changes meaning of 'handler' [-Wchanges-meaning]

FAILED: [code=1] src/libstore/libnixstore.so.2.35.0.p/misc.cc.o 
../src/libutil/include/nix/util/closure.hh:39:32: error: declaration of 'decltype (executor) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:71)>::State::executor' changes meaning of 'executor' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:40:32: error: declaration of 'decltype (getEdges) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:71)>::State::getEdges' changes meaning of 'getEdges' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:41:31: error: declaration of 'decltype (handler) nix::computeClosure(std::set<Input>, std::set<Input>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:71)>::State::handler' changes meaning of 'handler' [-Wchanges-meaning]

FAILED: [code=1] src/libutil-tests/nix-util-tests.p/closure.cc.o 
../src/libutil/include/nix/util/closure.hh:39:32: error: declaration of 'decltype (executor) nix::computeClosure(std::set<T>, std::set<T>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:66)>::State::executor' changes meaning of 'executor' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:40:32: error: declaration of 'decltype (getEdges) nix::computeClosure(std::set<T>, std::set<T>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:66)>::State::getEdges' changes meaning of 'getEdges' [-Wchanges-meaning]
../src/libutil/include/nix/util/closure.hh:41:31: error: declaration of 'decltype (handler) nix::computeClosure(std::set<T>, std::set<T>&, GetEdgesAsync<T>, CompletionToken&&)::<lambda(auto:66)>::State::handler' changes meaning of 'handler' [-Wchanges-meaning]
```

## Affected files

All translation units that include `closure.hh`:
- `src/libstore/http-binary-cache-store.cc`
- `src/libstore/misc.cc`
- `src/libutil-tests/closure.cc`

## Reproduction

```bash
git checkout 256877095  # current origin/master
nix develop -c bash -c 'meson setup build --buildtype=debugoptimized && ninja -C build'
```

## Environment

- GCC 14.3.0 (from nixpkgs)
- `nix develop` shell on NixOS

## Bisect

- Last good: `04e261a2a` (master before #15474 merge)
- First bad: `5e3c9f909` (merge of #15474)
- Root cause commit: `47d2d18` ("Make computeClosure async")

**Comment by xokdvium** [comment]
Do we actually enable this warning anywhere, or does this come from meson's warning level? TBH this seems like a pretty useless warning, since naming a class member the same as variable in the outer lexical scope is perfectly fine and unambiguous. Also, how come we are not hitting this in CI?

**Comment by randomizedcoder** [comment]
Good questions.

**Where does the warning come from?** `-Wchanges-meaning` is enabled by default in GCC's C++ mode and is treated as an **error by default** (not just a warning). It's not explicitly enabled anywhere in the meson build — GCC turns it on automatically. The project does use `warning_level=1` (which maps to `-Wall`), but `-Wchanges-meaning` is separate from `-Wall` and is on regardless.

Verified locally:

```
$ g++ -Q --help=warning 2>&1 | grep changes-meaning
  -Wchanges-meaning           		[enabled]
```

And a minimal reproducer errors out with just `g++ -std=c++23 -c`:

```
error: declaration of '...' changes meaning of 'executor' [-Wchanges-meaning]
```

**Why doesn't CI hit this?** CI uses `clangStdenv` (found in `.github/workflows`):

```yaml
stdenv: clangStdenv
```

Clang doesn't implement `-Wchanges-meaning`, so this is a GCC-only build failure. Anyone building with `nix develop` (which uses the default GCC stdenv) on current master will hit it.

**Comment by randomizedcoder** [comment]
Maybe as part of https://github.com/NixOS/nix/pull/15450 I could also switch nix develop to match the CI?

**Comment by xokdvium** [comment]
CI builds both with gcc and clang and there's no error.

**Comment by randomizedcoder** [comment]
Thanks for the correction — you're right, CI does build with both GCC and clang. I dug into this more and I think I understand why CI passes with GCC while `nix develop` doesn't.

**The difference is `-isystem` vs `-I`.**

In CI, each component is built as a separate Nix derivation via [`nix build --file ci/gha/tests/wrapper.nix`](https://github.com/NixOS/nix/blob/5df488fc7a247c5e090b872b2b3c9a376ec8365d/.github/workflows/ci.yml#L105-L107). When `nix-store` depends on `nix-util`, the nix-util headers end up installed in `/nix/store/.../include/` and the nixpkgs cc-wrapper setup hook adds them via **`-isystem`** — which tells GCC to treat them as system headers, suppressing all warnings including `-Wchanges-meaning`.

In `nix develop`, all subprojects are compiled together via meson's `subproject()` mechanism. The dependency is wired through [`meson.override_dependency()`](https://github.com/NixOS/nix/blob/5df488fc7a247c5e090b872b2b3c9a376ec8365d/nix-meson-build-support/export/meson.build#L32-L40) with `include_directories : include_dirs` (line 35), which produces regular **`-I`** flags. GCC treats these as user headers and applies the full set of diagnostics, including the [`-Wchanges-meaning` error on these three lines in `closure.hh`](https://github.com/NixOS/nix/blob/5df488fc7a247c5e090b872b2b3c9a376ec8365d/src/libutil/include/nix/util/closure.hh#L39-L41).

So the code triggers a real GCC diagnostic — it's just that the CI build path happens to hide it via system-header treatment.

**The fix itself is pretty small** — extracting type aliases before the struct so that `decltype` resolves in the outer lambda scope, avoiding the name-changes-meaning issue inside the struct body:

Before:
```cpp
        struct State : std::enable_shared_from_this<State>
        {
            decltype(executor) executor;
            decltype(getEdges) getEdges;
            decltype(handler) handler;
            std::set<T> & res;
            asio::executor_work_guard<decltype(State::executor)> workGuard;
            // ...

            State(
                decltype(executor) executor_, decltype(getEdges) getEdges, decltype(handler) handler, std::set<T> & res)
                : executor(executor_)
                // ...
```

After:
```cpp
        using ExecutorT = decltype(executor);
        using GetEdgesT = decltype(getEdges);
        using HandlerT = decltype(handler);

        struct State : std::enable_shared_from_this<State>
        {
            ExecutorT executor;
            GetEdgesT getEdges;
            HandlerT handler;
            std::set<T> & res;
            asio::executor_work_guard<ExecutorT> workGuard;
            // ...

            State(
                ExecutorT executor_, GetEdgesT getEdges, HandlerT handler, std::set<T> & res)
                : executor(executor_)
                // ...
```

All the method bodies (`state->executor`, `state->getEdges`, `state->handler`) remain unchanged. Happy to put up a small PR if this seems worthwhile, or happy to close the issue if you'd rather leave it as-is — it only affects `nix develop` with GCC.

However, probably the more important improvement would be to align `nix develop` and the CI pipelines so they match. The `-isystem` vs `-I` difference means `nix develop` is seeing a stricter set of diagnostics than CI does — which makes me a bit worried that local testing via `nix develop` isn't actually the same as what CI runs.

**Comment by xokdvium** [comment]
Sure, you can put up a PR.

> would be to align nix develop and the CI pipelines so they match

Not sure this is possible tbh.

**Comment by xokdvium** [comment]
> Not sure this is possible tbh.

Would be nice if there's a way to make compiler wrappers not do that.
