### ISSUE TITLE
Build failing on i636 and aarch64-linux

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#8523]
**Describe the bug**

The aarch64-linux (amongst others) broke on hydra somewhere between 468add5aa0b5b0a686cd07aa5417817bb8799602 and 05eb06a1deffba33c5f0012822c1a6d8832e5b49 .

**Steps To Reproduce**

Look at https://hydra.nixos.org/build/224230981#tabs-summary

**Additional context**

Briefly looking at the history between the last good and first bad commit, the most likely offender is https://github.com/NixOS/nix/commit/e377746842c1ae07dd6c4fdf6aa7eb0002b5cdcf (cc @Ericson2314 @wentasah )

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Indeed @wentasah, I didn't check that they were two different failures. I'll look into it

**Comment by wentasah** [comment]
The aarch64-linux build failed with

    src/libexpr/primops/context.cc:19:2: error: call of overloaded 'RegisterPrimOp(<brace-enclosed initializer list>)' is ambiguous

It seems that the failure is already fixed by #8516. It removes the second constructor, which caused the ambiguity. I'm not sure, why the same error did not appear in x86_64-linux too. Do aarch64 and x86_64 use different compiler versions or flags?

**Comment by thufschmitt** [comment]
> It seems that the failure is already fixed by https://github.com/NixOS/nix/pull/8516.

Oh, awesome! I'll just wait for https://hydra.nixos.org/build/224275005 to finish to be sure, and then we can close this.

> Do aarch64 and x86_64 use different compiler versions or flags?

Aah yes, aarch64 is stuck on an older GCC (9.5.0) because Nixpkgs is (dunno why), and we follow whatever the default is there.

**Comment by thufschmitt** [comment]
I've just submitted #8525 to fix the i686 builds

**Comment by thufschmitt** [comment]
Seems good now! Hydra is still red on master, but that's an instance of https://github.com/NixOS/nix/issues/7370 so we can close this
