### ISSUE TITLE
Nix fails to build on Fedora 26

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nix#1738]
Building the latest Nix from Git (1dffbff57d427da098bb750b5a86e57d7d0a401b) fails on Fedora 26:

  CXX    src/libstore/nar-accessor.o
In file included from src/libstore/nar-accessor.cc:1:0:
src/libstore/nar-accessor.hh:15:14: error: ‘function’ in namespace ‘std’ does not name a template type
 typedef std::function<std::string(uint64_t, uint64_t)> GetNarBytes;
              ^~~~~~~~
src/libstore/nar-accessor.hh:19:5: error: ‘GetNarBytes’ has not been declared
     GetNarBytes getNarBytes);
     ^~~~~~~~~~~
src/libstore/nar-accessor.cc:33:5: error: ‘GetNarBytes’ does not name a type
     GetNarBytes getNarBytes;
     ^~~~~~~~~~~
src/libstore/nar-accessor.cc:110:46: error: ‘GetNarBytes’ has not been declared
     NarAccessor(const std::string & listing, GetNarBytes getNarBytes)
                                              ^~~~~~~~~~~
src/libstore/nar-accessor.cc: In constructor ‘nix::NarAccessor::NarAccessor(const string&, int)’:
src/libstore/nar-accessor.cc:111:11: error: class ‘nix::NarAccessor’ does not have any field named ‘getNarBytes’
         : getNarBytes(getNarBytes)
           ^~~~~~~~~~~
src/libstore/nar-accessor.cc: In member function ‘virtual std::__cxx11::string nix::NarAccessor::readFile(const Path&)’:
src/libstore/nar-accessor.cc:202:13: error: ‘getNarBytes’ was not declared in this scope
         if (getNarBytes) return getNarBytes(i.start, i.size);
             ^~~~~~~~~~~
src/libstore/nar-accessor.cc:202:13: note: suggested alternative: ‘getdate’
         if (getNarBytes) return getNarBytes(i.start, i.size);
             ^~~~~~~~~~~
             getdate
src/libstore/nar-accessor.cc: At global scope:
src/libstore/nar-accessor.cc:223:5: error: ‘GetNarBytes’ has not been declared
     GetNarBytes getNarBytes)
     ^~~~~~~~~~~
make: *** [mk/patterns.mk:3: src/libstore/nar-accessor.o] Error 1

**Comment by armijnhemel** [comment]
88ef77226e0a395a0151297c295843d2e39f24d5 builds

**Comment by armijnhemel** [comment]
bug was introduced after 2fd8f8bb99a2832b3684878c020ba47322e79332

**Comment by armijnhemel** [comment]
confirmed that the fix works, thanks.
