### PR TITLE
Escape square brackets in configure.ac

### PR DESCRIPTION
**Pull request by 0mp**
This patch attempts to solve the regression introduced in e8b0efdc
(#2607).

It wasn't detected by me before the previous commit because GNU grep behaviour for `egrep '^_[:alpha:]_[:alnum:]*$'` varies across versions:
- grep (GNU grep) 2.5.1-FreeBSD does not report any issues
- grep (GNU grep) 3.3 prints the following message:

    >     /bin/grep: character class syntax is [[:space:]], not [:space:]

### CODE REVIEW

**Comment by kirelagin** [comment]
Now it gets turned into `'^[_[[:alpha:]]][_[[:alnum:]]]*$'`, which still doesn’t look right. Looks like the inner pair of brackets does not need to be escaped.

**Comment by kirelagin** [comment]
I’ve got another regression. It looks a lot like it was introduced by the same commit.

```
src/libstore/s3-binary-cache-store.cc:95:23: error: invalid token at start of a preprocessor expression
#if AWS_VERSION_MAJOR == 1 && AWS_VERSION_MINOR < 3
```

in `config.status`:

```
D["AWS_VERSION_MAJOR"]=" "
D["AWS_VERSION_MINOR"]=" "
```

**Comment by edolstra** [comment]
I've reverted this and the previous commit for now.
