### ISSUE TITLE
Nix on Cygwin doesn't work because DBD::SQLite doesn't work

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#19]
```
$ perl -e 'use DBD::SQLite;'
Can't load '/nix/store/nxy9c2s5443al8g601fjlg62idbzqh0w-perl-DBD-SQLite-1.35/lib/perl5/site_perl/5.10/i686-cygwin/auto/DBD/SQLite/SQLite.dll' for module DBD::SQLite: No such process at /usr/lib/perl5/5.10/i686-cygwin/DynaLoader.pm line 200.
 at -e line 1
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

The "No such process" error may be related to the base address of the DLL, but changing it using the "--image-base=..." linker flag didn't help.  Running "rebaseall" didn't help either (but then it doesn't look in the Nix store so that's not surprising).

**Comment by tohl** [comment]
nix builds on cygwin-nt 6.1 2.2.0 (0.289/5/3) x86_64
i roughly followed https://nixos.org/wiki/Nix_on_Windows which gives an idea but most of the dependencies i had to install manually via cygwin gui
after building nix, i can install hello, for example
many packages don't work, but that is a problem with nixpkgs, not nix

**Comment by chaoflow** [comment]
This issue is outdated and should be closed.

@tohl thx for reporting

**Comment by chaoflow** [comment]
For completeness: we describe a cygport file to install nix on cygwin: http://ternaris.com/lab/nix-on-windows.html#package-build-and-install-nix

**Comment by tohl** [comment]
actually the version that builds under cygwin is nix-1.8

the latest nix from unstable doesn't build because of a compilation error
undefined ENOENT in nix-collect-garbage.cc
adding #include <errno.h> might fix this issue

**Comment by ryantrinkle** [comment]
My company, [Obsidian Systems](https://obsidian.systems) would be interested in helping to support development of a Windows distribution of Nix.  If anyone is interested in working on this or helping support it, please send me an email at [ryan@obsidian.systems](mailto:ryan@obsidian.systems).

**Comment by vcunat** [comment]
@ryantrinkle: this particular issue will preferably be addressed by #341, IMHO.

**Comment by domenkozar** [comment]
@ryantrinkle "Windows distribution of Nix" meaning natively without cygwin?

**Comment by domenkozar** [comment]
As stated by @chaoflow this is outdated and we're very close to being perl free.
