### PR TITLE
Properly set _POSIX_C_SOURCE macro.

### LINKED ISSUE #1013: darwin: build failures due to O_CLOEXEC being only conditionally defined
Commit 202683a4fc148dc228de226e9980a3f27754b854 introduced the use of O_CLOEXEC which, when I build on my Mac OS X El Capitan 10.11.6 system with nixpkgs set to a recent channels/nixpkgs-unstable checkout like so:

```
git clone https://github.com/nixos/nix
cd nix; nix-build -I nixpkgs=~/nixpkgs release.nix -A build.x86_64-darwin
```

produces build failures like so:

```
src/libutil/archive.cc:44:52: error: use of undeclared identifier 'O_CLOEXEC'
    AutoCloseFD fd = open(path.c_str(), O_RDONLY | O_CLOEXEC);
```

because `O_CLOEXEC` is only *conditionally* defined in `<sys/fcntl.h>` when `__DARWIN_C_LEVEL` is set appropriately:

```
#if __DARWIN_C_LEVEL >= 200809L
#define O_CLOEXEC       0x1000000       /* implicitly set FD_CLOEXEC */
#endif
```

Python and D-Bus both have tickets about similar problems, though unfortunately I don't yet understand how they fixed things:

  * http://bugs.python.org/issue26343
  * https://bugs.freedesktop.org/show_bug.cgi?id=77032

(That said, is the build command above expected to build cleanly on Darwin?)

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #1013

### CODE REVIEW

**Comment by shlevy** [comment]
@mstone please test

**Comment by mstone** [comment]
With this patch, building fails in `./configure` with

```
checking if your system supports a recent POSIX... configure: error: in `/private/var/folders/yr/jy2x3w_92xz0kcr3fr33vnx8000wkg/T/nix-build-nix-tarball-1.12pre1234_abcdef.drv-0/nix':
configure: error: *** Implementation must conform to the POSIX.1-2008 standard.
See `config.log' for more details
```

I think because OS X sets `#define _POSIX_VERSION 200112L` in `/usr/include/sys/unistd.h` included in `/usr/include/unistd.h` presumably because while it apparently implements some portions of POSIX.1-2008, it doesn't promise to implement them all?

**Comment by shlevy** [comment]
Damn, OK, I'll remove that check

**Comment by mstone** [comment]
Some additional thoughts:

1. Some people on the python bug tracker think that the preprocessor macros we're considering usually get set by choosing an appropriate "Mac OS X deployment target", either via the `MACOSX_DEPLOYMENT_TARGET` environment variable or via the `-mmacosx-version-min` command line flag (both of which apparently do the same thing but where the command-line flag takes priority when both are specified).

2. As a result, I looked at the `env-vars` file left behind by the failed `nix-build -K ...` command I ran and, sure enough, we're apparently targeting OS X 10.7:
  
    ```
    ...
    declare -x MACOSX_DEPLOYMENT_TARGET="10.7"
    ...
    ```
  
    ... assuming that the C/C++ toolchain that Nix is using is sensitive to this environment variable in the same way that the Apple toolchain is.

3. Thus...

    a) How confident are we that 10.7 is a good OS X version to target?

    b) How confident are we that the Nix-provided toolchain uses this input sensibly?

    c) Should we keep going about this by trying to choose a standard to test for support of, e.g., vs. by choosing which OS X minimum versions we want to support?

    d) ...?

**Comment by shlevy** [comment]
@mstone Can you try this version?

**Comment by shlevy** [comment]
pinging @copumpkin and @pikajude for the MACOSX_DEPLOYMENT_TARGET questions

**Comment by mstone** [comment]
@shlevy -- happy to but, re: choosing an appropriate deployment target, Apple API diffs suggest that `O_CLOEXEC` support was added in [OS X 10.10](https://developer.apple.com/library/mac/documentation/General/Reference/APIDiffsMacOSX10_10SeedDiff/modules/Darwin.html).

**Comment by mstone** [comment]
@shlevy -- with the revised patch, `./configure` completes but the build fails with a new problem:

```
  CXX    src/libexpr/primops.o
src/libexpr/primops.cc:828:25: error: use of undeclared identifier 'DT_UNKNOWN'
        if (ent.type == DT_UNKNOWN)
                        ^
src/libexpr/primops.cc:831:25: error: use of undeclared identifier 'DT_REG'
            ent.type == DT_REG ? "regular" :
                        ^
src/libexpr/primops.cc:832:25: error: use of undeclared identifier 'DT_DIR'
            ent.type == DT_DIR ? "directory" :
                        ^
src/libexpr/primops.cc:833:25: error: use of undeclared identifier 'DT_LNK'
            ent.type == DT_LNK ? "symlink" :
                        ^
4 errors generated.
make: *** [mk/patterns.mk:3: src/libexpr/primops.o] Error 1
```

perhaps because, per [OS X man 2 direntries](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getdirentries.2.html),  `primops.cc` needs to include `<sys/dirent.h>` on OS X and because `<sys/dirent.h>` only defines `DT_REG` + friends when 

```
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
```

?

**Comment by shlevy** [comment]
Oy. Probably the answer is just target 10.10. But I'll leave that to the other darwin users.
