### ISSUE TITLE
installation of nvidia legacy 340 driver fails on upgrade to 21.05

### ISSUE THREAD

**Issue by jkozak** [NixOS/nix#4970]
**Describe the bug**

I am trying to upgrade nixos to 21.05.  I have an antique nvidia card which requires the legacy 340 drivers and I have set up `configuration.nix` so:

```
  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_340;
  services.xserver.layout = "gb";
```

when I do `nixos-rebuild --upgrade switch` it fails so (on multiple files):

```
In file included from /build/kernel/nv-acpi.c:15:
/build/kernel/nv-linux.h: At top level:
/build/kernel/nv-linux.h:139:10: fatal error: linux/ioctl32.h: No such file or directory
  139 | #include <linux/ioctl32.h>          /* register_ioctl32_conversion()    */
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
**`nix-env --version` output**
```
nix-env (Nix) 2.3.11
```
[nixos-rebuild.log](https://github.com/NixOS/nix/files/6749194/nixos-rebuild.log)

**Comment by bjornfor** [comment]
NixOS 21.05 upgraded the default Linux kernel version. Perhaps you can get it working by selecting an older kernel version?

**Comment by jkozak** [comment]
It builds on kernel 5.4 - thanks!

**Comment by Ericson2314** [comment]
Wrong repo?

**Comment by RinatKurmaev** [comment]
> It builds on kernel 5.4 - thanks!

How did you manage to do that. Can you provide the example of your configuration?

**Comment by vcunat** [comment]
@RinatKurmaev: that's basic NixOS config
```
boot.kernelPackages = pkgs.linuxPackages_5_4;
```
