### PR TITLE
packaging: Use correct stdenv for x86_64-darwin

### LINKED ISSUE #12552: x86_64-darwin build broken
## Describe the bug

https://hydra.nixos.org/build/290788151

```
../nix_api_expr.cc:38:18: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer
    void * p = ::operator new(
                 ^
../nix_api_expr.cc:38:18: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
1 error generated.
```

Seems to be introduced in 82a23d9b6b96bf08e7c28008fcc346c0bdb671be. @roberth 

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by roberth**
## Motivation

- Closes #12552

## Context

- https://github.com/NixOS/nix/pull/11144

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: packaging/components.nix [hunk 1]
```diff
@@ -12,6 +11,15 @@ let
...
     ;
+  inherit
+    (scope.callPackage (
+      { stdenv }:
+      {
+        inherit stdenv;
+      }
+    ) { })
+    stdenv
+    ;
```
Comment (roberth) [inline packaging/components.nix:22]: Not pretty. Will consider moving the build utilities to their own file, and then `callPackage` that.

**Review by edolstra — APPROVED** [review]

File: packaging/components.nix (hunk 1 above)
Comment (roberth) [reply packaging/components.nix:22]: Either way we aren't making much use of the two layers of scoping, and we could simplify by squashing those into one scope. I'd keep the separate file for dependencies, but wire it up with `import` and `//` - should be simple enough.
