### ISSUE TITLE
local-derivation-goal.cc needs to include sys/socket.h for definition of SHUT_RDWR and socklen_t

### ISSUE THREAD

**Issue by greedy** [NixOS/nix#5282]
https://github.com/NixOS/nix/blob/c81f9761ccb40865edc497321752503abc0da858/src/libstore/build/local-derivation-goal.cc#L1387

The build failure in https://github.com/NixOS/nixpkgs/pull/138623 seems to be a result of the removal of the include of `sys/socket.h` in local-derivation-goal.cc in 3b72741f23a854d351db8c1d76a74c9255141873:

```
src/libstore/build/local-derivation-goal.cc:1350:13: error: unknown type name 'socklen_t'
            socklen_t remoteAddrLen = sizeof(remoteAddr);
            ^
src/libstore/build/local-derivation-goal.cc:1387:54: error: use of undeclared identifier 'SHUT_RDWR'
    if (daemonSocket && shutdown(daemonSocket.get(), SHUT_RDWR) == -1)
                                                     ^
```

POSIX documents [shutdown() as requiring sys/socket.h](https://pubs.opengroup.org/onlinepubs/9699919799/functions/shutdown.html) and [sys/socket.h as providing socklen_t](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html). I'm not sure what leads to these definitions still being available on the linux builds.

I'm unfortunately not able to test and verify this fixes the issue right now on my own.
