### ISSUE TITLE
buildStatic.nix-*-tests fails to build

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#12285]
## Describe the bug

For example, from https://hydra.nixos.org/build/285560922:
```
[2/2] Linking target test-libstoreconsumer/test-libstoreconsumer
FAILED: test-libstoreconsumer/test-libstoreconsumer 
x86_64-unknown-linux-musl-g++  -o test-libstoreconsumer/test-libstoreconsumer test-libstoreconsumer/test-libstoreconsumer.p/main.cc.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -pthread -Wl,--start-group /nix/store/2hbky50x3hzky0drn4ay87xj77frq27c-boost-static-x86_64-unknown-linux-musl-1.81.0/lib/libboost_container.a /nix/store/2hbky50x3hzky0drn4ay87xj77frq27c-boost-static-x86_64-unknown-linux-musl-1.81.0/lib/libboost_context.a /nix/store/2hbky50x3hzky0drn4ay87xj77frq27c-boost-static-x86_64-unknown-linux-musl-1.81.0/lib/libboost_coroutine.a -lm -lpthread -ldl -L/nix/store/iyfx3gjvyg6a616wvafs2jr8331iggvm-nix-store-static-x86_64-unknown-linux-musl-2.26.0pre/lib -L/nix/store/hg2jizgz4nvg3j775ydyyy0sak65zlr2-nix-util-static-x86_64-unknown-linux-musl-2.26.0pre/lib -L/nix/store/9ry58m62d5b1b5w162szl35y33bay61a-zlib-static-x86_64-unknown-linux-musl-1.3.1/lib -L/nix/store/w9vh0sg61byq8am2110na6zchzb1y8hj-zstd-static-x86_64-unknown-linux-musl-1.5.6/lib -L/nix/store/cxh2dbw8d6wwx52ln866i61z25vdfssj-libarchive-static-x86_64-unknown-linux-musl-3.7.7-lib/lib -L/nix/store/7zxrnwfyzahyi129kzvlns5vywnnv46q-libxml2-static-x86_64-unknown-linux-musl-2.13.4/lib -L/nix/store/wp1xrc7cf57dshj4b3zxkdxmbib7lwnv-openssl-static-x86_64-unknown-linux-musl-3.3.2/lib -L/nix/store/y7hk65i4iv8bfbx1cgx4srks7ip5gpha-brotli-static-x86_64-unknown-linux-musl-1.1.0-lib/lib -L/nix/store/lir8drwb4hvb2s92s65zpf9189pj55li-libsodium-static-x86_64-unknown-linux-musl-1.0.20/lib -L/nix/store/7g1zbbkbfxbbc16riqi6a3hx58a4z27a-curl-static-x86_64-unknown-linux-musl-8.11.0/lib -L/nix/store/yscw94waiankc8crbinsk7fkdil8lalg-libpsl-static-x86_64-unknown-linux-musl-0.21.5/lib -L/nix/store/nqgz57gbp477zrfp18k1xm42qxh9f0bx-libidn2-static-x86_64-unknown-linux-musl-2.3.7/lib -L/nix/store/6c7sim40arq2xpilip2kwba78npzxqnw-nghttp2-static-x86_64-unknown-linux-musl-1.64.0-lib/lib -L/nix/store/z33gl8bwvrl5l1psqdqsws3fp67zs0rv-libssh2-static-x86_64-unknown-linux-musl-1.11.1/lib -L/nix/store/hpwsk58fs3mmanmsz9gi0g32lrc8ilj0-sqlite-static-x86_64-unknown-linux-musl-3.46.1/lib -L/nix/store/407m1vh8q111gkcbdmagivgvi73fqygj-libseccomp-static-x86_64-unknown-linux-musl-2.5.5-lib/lib -L/nix/store/0gs2zqk4w9gp61vfkfg0dbzcd5q6bmsl-libcpuid-static-x86_64-unknown-linux-musl-0.7.0/lib -L/nix/store/1wswmmpv740g24lrxajn15bqglrc8bci-libssh2-static-x86_64-unknown-linux-musl-1.11.1-dev/lib -lnixstore -lnixutil -larchive -lcrypto -lacl -llzma -lzstd -lbz2 -lz -lxml2 -lsodium -lbrotlidec -lbrotlienc -lbrotlicommon -lcpuid -lcurl -lnghttp2 -lidn2 -lunistring -lssh2 -lpsl -lssl -lseccomp -lsqlite3 -Wl,--end-group
/nix/store/v91isjx13173ylh3vq43bdw4wcz2afjj-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: /build/ccfnH6Qp.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0xd8): undefined reference to `nix::initLibStore(bool)'
/nix/store/v91isjx13173ylh3vq43bdw4wcz2afjj-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: <artificial>:(.text.startup+0x121): undefined reference to `nix::settings'
/nix/store/v91isjx13173ylh3vq43bdw4wcz2afjj-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: <artificial>:(.text.startup+0x132): undefined reference to `nix::openStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/nix/store/v91isjx13173ylh3vq43bdw4wcz2afjj-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: <artificial>:(.text.startup+0x179): undefined reference to `nix::StoreDirConfig::parseStorePath(std::basic_string_view<char, std::char_traits<char> >) const'
/nix/store/v91isjx13173ylh3vq43bdw4wcz2afjj-x86_64-unknown-linux-musl-binutils-2.43.1/bin/x86_64-unknown-linux-musl-ld: <artificial>:(.text.startup+0x5a2): undefined reference to `nix::StoreDirConfig::printStorePath[abi:cxx11](nix::StorePath const&) const'
collect2: error: ld returned 1 exit status
```

Looking at the first failing build, this may have been caused by #12097.

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
