### ISSUE TITLE
New dep on boost not in the ./configure

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nix#1975]
Hello,

It looks like that some changes has been made to the deps today about boost, and that now one need to install more deps (I was able to git download & compile this morning, but not tonight with the exact same code). To be more precise, the `./configure` runs smoothly, but then the make fails:

```
$ make
  GEN    Makefile.config
  GEN    src/libexpr/parser-tab.cc
  GEN    src/libexpr/lexer-tab.cc
  CXX    src/linenoise/ConvertUTF.o
  CXX    src/linenoise/linenoise.o
  CXX    src/linenoise/wcwidth.o
  CXX    src/nix/add-to-store.o
In file included from src/libutil/util.hh:3:0,
                 from src/libutil/args.hh:7,
                 from src/nix/command.hh:3,
                 from src/nix/add-to-store.cc:1:
src/libutil/types.hh:12:10: fatal error: boost/format.hpp: Aucun fichier ou dossier de ce type
 #include <boost/format.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

Installing `libboost-dev` fix the problem, but the `./configure` and the manual should mention this new dep.  By the way, I thought that nix wanted to use as few deps as possible, so is it wanted to add `libboost-dev` in the deps?

Thank you!

**Comment by lanceman2** [comment]
Q1: I have a related problem when building from git repo source from URL https://github.com/NixOS/nix/tarball/2.3.7 on Ubuntu 20.04.1 with package *libboost-all-dev* installed.   *./bootstrap.sh* fails.  There is no m4 macro AX_BOOST_BASE.  There are no boost m4 macros on the system.  Is there a URL where we can get the needed boost m4 macro functions?  Ubuntu seems to have left out the boost m4 macros.

I'm able to build and install from the tarball release nix-2.3.7, but building from a git repo checkout is not working on Ubuntu 20.04.1.   Is Ubuntu 20.04.1 a package target OS?

Q2: Why is this issue still labeled "build-problem"?  The first comment seems to resolve it.   I add this comment here because this is directly related.  I'm trying to keep sense in the issues, and not pollute this forum.  Had tobiasBora tried to build from git repo source, it's likely that they would have hit this m4 problem too, and the title "New dep on boost not in the ./configure" fits this m4 boost issue I'm having, with the configure I generate being broken due to the boost dependency.  I think that this (year 2018) issue should have been closed, but because it is not I put this here and not make a new issue.

**Comment by L-as** [comment]
I'm having this issue now.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
